/**
 * @file Timer_A0_PWM.h
 * @brief Header file for the Timer_A0_PWM driver.
 *
 * This file contains the function definitions for configuring Timer A0 in Pulse Width Modulation (PWM) mode.
 * It provides functions for initializing the PWM timer, updating duty cycles for PWM signals, and controlling
 * the PWM output on specific pins.
 *
 * @note The Motor driver uses Timer_A0_PWM as a base driver.
 *
 * @author Aaron Nanas
 *
 */

#ifndef INC_TIMER_A0_PWM_H_
#define INC_TIMER_A0_PWM_H_

#include <stdint.h>
#include "msp.h"

// Constant used to define the period of the PWM signal generated by Timer A0
// General formula: Period = (2*period_constant) / (12 MHz / Prescale Value)
// In this case: Period = (2*15000) / (12 MHz / 8) = 20 ms
#define TIMER_A0_PERIOD_CONSTANT 15000

/**
 * @brief
 ***
 * This function initializes Timer A0 to generate two PWM signals on P2.6 and P2.7.
 * It first checks to see if either duty cycle value is greater than or equal to the period constant, the
 * function exits immediately if that is the case. Otherwise, it configures
 * P2.6 and P2.7 to use the peripheral function mode by setting Bits 6 and 7 of the
 * SEL0 register and clearing Bits 6 and 7 of the SEL1 register. The pins are also
 * configured as outputs by setting Bits 6 and 7 of the DIR register. The function
 * then assigns the period constant to the CCR[0] register and clears all of the bits
 * in the EX0 register. The OUTMOD fields of the CCTL[3] and CCTL[4] registers are
 * set to "010" to select the Toggle/Reset output mode, and the duty cycle values are
 * assigned to CCR[3] and CCR[4]. Finally, it modifies the CTL register so that
 * Timer A0 uses SMCLK (12 MHz) as the clock source, divides the timer clock by 8
 * (ID = 3), and enables Up/Down mode (MC = 3).
 *
 *

 * @param period_constant
 *
 * @param duty_cycle_1
 *
 * @param duty_cycle_2
 *
 * @return None
 */
void Timer_A0_PWM_Init(uint16_t period_constant, uint16_t duty_cycle_1, uint16_t duty_cycle_2);

/**
 * @brief Update the Timer A0 duty cycle for the PWM signal, P2.6 (PM_TA0.3, CCR[3])
 *
 * @param duty_cycle_1 The new duty cycle for the PWM signal, P2.6 (PM_TA0.3, CCR[3])
 *
 * @return None
 */
void Timer_A0_Update_Duty_Cycle_1(uint16_t duty_cycle_1);

/**
 * @brief Update the Timer A0 duty cycle for the PWM signal, P2.7 (PM_TA0.4, CCR[4])
 *
 * @param duty_cycle_2 The new duty cycle for the PWM signal, P2.7 (PM_TA0.4, CCR[4])
 *
 * @return None
 */
void Timer_A0_Update_Duty_Cycle_2(uint16_t duty_cycle_2);

#endif /* INC_TIMER_A0_PWM_H_ */
